(define (smallest-divisor n)
  (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))))
(define (divides? a b)
  (= (remainder b a) 0))

(define (prime? n)
  (= n (smallest-divisor n)))

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))


(define (search-for-primes start end) 
  (if (<= start end)
    (timed-prime-test start)
    )
  (if (<= start end)
    (search-for-primes (+ 2 start) end)
    )
  )
(search-for-primes 999 1019)
(search-for-primes 9999 10037)
(search-for-primes 99999 100043)
(search-for-primes 999999 1000037)
